openapi: 3.0.3
info:
  title: E*TRADE Authorization API
  version: "1.0.0"
servers:
  - url: https://api.etrade.com

paths:
  /oauth/request_token:
    get:
      summary: Get Request Token
      description: Initiates the OAuth process by returning a temporary request token.
      operationId: getRequestToken
      responses:
        '200':
          description: Successful Operation.
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  oauth_token:
                    type: string
                  oauth_token_secret:
                    type: string
                  oauth_callback_confirmed:
                    type: string
        '400':
          description: There is issue with input
        '500':
          description: An unexpected error has occurred. The error has been logged and is being investigated.

components: {}
security: []